results:
  linear_regression:
    features:
    - retail_sales_apparel_ewm_12_backshift_12
    - cpi_u_ewm_3_backshift_12
    - New_Sales_mean_this_year_ewm_6_backshift_12
    - New_Sales_std_this_year_ewm_12_backshift_12
    - cpi_u_backshift_12
    - Budget_USD_std_this_year_lag_3
    - New_Sales_std_this_year_ewm_6_backshift_12
    - cpi_u_lag_3_backshift_12
    - New_Sales_std_this_year_ewm_3_backshift_12
    - Budget_USD_mean_this_year_ewm_12
    - Budget_USD_std_this_year_ewm_3
    - Budget_USD_mean_this_year_ewm_6
    - Budget_USD_std_this_year_ewm_12
    - retail_sales_apparel_ewm_3_backshift_12
    - Budget_USD_std_this_year_lag_6
    - Budget_USD_std_this_year
    - Budget_USD_std_this_year_lag_12
    - cpi_u_ewm_6_backshift_12
    - gdp_ewm_3_backshift_12
    - New_Sales_std_this_year_lag_3_backshift_12
    - cpi_u_ewm_12_backshift_12
    - Budget_USD_ewm_6
    - New_Sales_ewm_6_backshift_12
    - Budget_USD_mean_this_year_ewm_3
    - New_Sales_mean_this_year_ewm_12_backshift_12
    - New_Sales_ewm_12_backshift_12
    - New_Sales_std_this_year_backshift_12
    - Budget_USD_mean_this_year
    - Budget_USD_std_this_year_ewm_6
    - New_Sales_mean_this_year_lag_3_backshift_12
    - cpi_u_lag_6_backshift_12
    - Budget_USD_mean_this_year_lag_12
    - New_Sales_std_this_year_lag_6_backshift_12
    - gdp_backshift_12
    - pce_apparel_lag_3_backshift_12
    - Quarter_2
    - retail_sales_apparel_backshift_12
    - pce_apparel_backshift_12
    - Year
    - New_Sales_mean_this_year_lag_6_backshift_12
    - pce_apparel_ewm_6_backshift_12
    - Month_4
    - Month_2
    - Quarter_3
    - quarter_cos
    - Month_7
    - Close_gold_backshift_12
    - pce_apparel_ewm_3_backshift_12
    - Month_5
    - New_Sales_lag_3_backshift_12
    - Promo_Type_Cashback
    - Promo_Type_Discount
    - Promo_Type_No_Promo
    params:
      fit_intercept: 1
      positive: 1
  lightgbm:
    features:
    - Budget_USD
    - quarter_cos
    - month_cos
    - Budget_USD_ewm_3
    - month_sin
    - New_Sales_lag_6_backshift_12
    - New_Sales_ewm_3_backshift_12
    - Budget_USD_ewm_12
    - Budget_USD_std_this_quarter_ewm_6
    - Budget_USD_ewm_6
    - Budget_USD_std_this_year_ewm_6
    - Budget_USD_mean_this_year_ewm_12
    - Budget_USD_mean_this_quarter_ewm_12
    - Budget_USD_mean_this_year
    - Budget_USD_std_this_quarter_ewm_12
    - Budget_USD_std_this_year_ewm_12
    - Budget_USD_mean_this_quarter_ewm_6
    - Budget_USD_std_this_year_ewm_3
    - pce_apparel_ewm_3_backshift_12
    - Budget_USD_lag_12
    - Budget_USD_mean_this_quarter_lag_3
    - Budget_USD_mean_this_year_ewm_6
    - New_Sales_ewm_12_backshift_12
    - Budget_USD_mean_this_year_lag_12
    - New_Sales_ewm_6_backshift_12
    - New_Sales_lag_12_backshift_12
    - New_Sales_std_this_year_ewm_12_backshift_12
    - Close_gold_lag_6_backshift_12
    - New_Sales_std_this_year_ewm_6_backshift_12
    - Budget_USD_mean_this_year_lag_3
    - Month_8
    - Budget_USD_mean_this_quarter_lag_12
    - Budget_USD_lag_6
    - Close_gold_backshift_12
    - Month_12
    - Budget_USD_lag_3
    - Month_5
    - retail_sales_apparel_ewm_12_backshift_12
    - Budget_USD_std_this_quarter_lag_6
    - quarter_sin
    - Budget_USD_std_this_year_lag_3
    - Budget_USD_std_this_year
    - New_Sales_mean_this_year_ewm_6_backshift_12
    - New_Sales_mean_this_year_backshift_12
    - New_Sales_mean_this_year_ewm_3_backshift_12
    - New_Sales_mean_this_year_lag_12_backshift_12
    - New_Sales_mean_this_year_lag_3_backshift_12
    - New_Sales_mean_this_year_lag_6_backshift_12
    - Budget_USD_std_this_year_lag_12
    - budget_to_sales_backshift_12
    - Year
    - Quarter_4
    - Month_6
    - cpi_u_ewm_6_backshift_12
    - cpi_u_ewm_3_backshift_12
    - cpi_u_ewm_12_backshift_12
    - cpi_u_backshift_12
    - gdp_backshift_12
    - Close_gold_ewm_6_backshift_12
    - Close_gold_ewm_12_backshift_12
    - Quarter_3
    - Quarter_2
    - gdp_ewm_3_backshift_12
    - pce_apparel_backshift_12
    - cpi_u_lag_6_backshift_12
    - Month_7
    - Month_9
    - cpi_u_lag_3_backshift_12
    - Month_10
    - Month_3
    - pce_apparel_lag_3_backshift_12
    - pce_apparel_ewm_6_backshift_12
    - Month_2
    - Promo_Type_Cashback
    - Month_11
    - Promo_Type_No_Promo
    - Month_4
    - Promo_Type_Discount
    - New_Sales_std_this_year_lag_3_backshift_12
    - Budget_USD_std_this_year_lag_6
    params:
      num_leaves: 123
      max_depth: 2
      learning_rate: 0.06779805175596357
      n_estimators: 602
      subsample: 0.7077251073851982
      colsample_bytree: 0.6531658833229904
      reg_alpha: 0.0015993086707157258
      reg_lambda: 0.008262649661607592
      min_child_samples: 10
  catboost:
    features:
    - Budget_USD
    - quarter_cos
    - month_sin
    - Promo_Type_No_Promo
    - month_cos
    - Budget_USD_ewm_3
    - Budget_USD_ewm_6
    - Budget_USD_std_this_quarter_ewm_3
    - Quarter_3
    - Budget_USD_mean_this_quarter_ewm_6
    - New_Sales_lag_6_backshift_12
    - New_Sales_ewm_3_backshift_12
    - Budget_USD_std_this_quarter
    - Budget_USD_std_this_quarter_ewm_6
    - Budget_USD_mean_this_quarter
    - Promo_Type_Discount
    - Budget_USD_ewm_12
    - Budget_USD_mean_this_year
    - Budget_USD_std_this_quarter_ewm_12
    - Budget_USD_std_this_year_ewm_6
    - quarter_sin
    - New_Sales_std_this_year_lag_3_backshift_12
    - retail_sales_apparel_ewm_3_backshift_12
    - Budget_USD_mean_this_year_ewm_3
    - retail_sales_apparel_backshift_12
    - Quarter_4
    - Budget_USD_std_this_year
    - New_Sales_lag_12_backshift_12
    - Month_12
    - Budget_USD_mean_this_year_ewm_6
    - Budget_USD_mean_this_quarter_ewm_3
    - Month_8
    - Budget_USD_std_this_year_ewm_12
    - Budget_USD_mean_this_year_lag_3
    - Budget_USD_mean_this_year_ewm_12
    - Month_10
    - Budget_USD_std_this_quarter_lag_12
    - New_Sales_std_this_year_lag_6_backshift_12
    - gdp_backshift_12
    - Budget_USD_std_this_quarter_lag_6
    - Budget_USD_std_this_year_lag_12
    - New_Sales_std_this_year_backshift_12
    - pce_apparel_backshift_12
    - Budget_USD_mean_this_quarter_ewm_12
    - Budget_USD_mean_this_quarter_lag_12
    - Budget_USD_std_this_year_ewm_3
    - gdp_ewm_3_backshift_12
    - Budget_USD_lag_12
    - Month_9
    - New_Sales_ewm_6_backshift_12
    - New_Sales_std_this_year_ewm_6_backshift_12
    - Month_7
    - Budget_USD_std_this_year_lag_3
    - pce_apparel_ewm_3_backshift_12
    - New_Sales_std_this_year_ewm_12_backshift_12
    - pce_apparel_ewm_6_backshift_12
    - New_Sales_lag_3_backshift_12
    - New_Sales_std_this_year_ewm_3_backshift_12
    - Month_5
    - Month_11
    - Quarter_2
    - Month_4
    - Budget_USD_mean_this_year_lag_12
    - pce_apparel_lag_3_backshift_12
    - Budget_USD_lag_6
    - Month_2
    - Close_gold_ewm_6_backshift_12
    - Budget_USD_mean_this_quarter_lag_6
    - Close_gold_backshift_12
    - cpi_u_ewm_3_backshift_12
    - cpi_u_backshift_12
    - Budget_USD_lag_3
    - Month_3
    - cpi_u_ewm_6_backshift_12
    - New_Sales_mean_this_year_lag_3_backshift_12
    - Year
    - budget_to_sales_backshift_12
    - Promo_Type_Cashback
    - cpi_u_ewm_12_backshift_12
    - New_Sales_mean_this_year_lag_6_backshift_12
    params:
      depth: 4
      learning_rate: 0.05856899407992348
      iterations: 432
      l2_leaf_reg: 4.876111485633056
      random_strength: 0.3956876603220011
      bagging_temperature: 0.38489042971718207
      border_count: 181
      rsm: 0.6298622475240189
  lstm:
    features:
    - Budget_USD
    - New_Sales_lag_12
    - Quarter_3
    - Residual_lag
    - Quarter_4
    - Month_10
    - Month_7
    - Month_3
    - Month_2
    - Month_6
    - Month_4
    - Month_9
    - Month_12
    - Month_11
    - Month_8
    - Month_5
    - Promo_Type_Cashback
    - Year
    - Promo_Type_No_Promo
    - New_Sales_lag_15
    - Promo_Type_Discount
    - Trend_lag
    - Quarter_2
    params:
      lr: 0.00810675450542961
      units: 80
      batch_size: 16
      patience: 12
  rnn:
    params:
      lr: 0.009637842250219264
      units: 112
      batch_size: 16
      patience: 12
    features:
    - Budget_USD
    - New_Sales_lag_12
    - Quarter_3
    - Residual_lag
    - Quarter_4
    - Month_10
    - Month_7
    - Month_3
    - Month_2
    - Month_6
    - Month_4
    - Month_9
    - Month_12
    - Month_11
    - Month_8
    - Month_5
    - Promo_Type_Cashback
    - Year
    - Promo_Type_No_Promo
    - New_Sales_lag_15
    - Promo_Type_Discount
    - Trend_lag
    - Quarter_2
  lstm_2025:
    features:
    - Budget_USD
    - New_Sales_lag_12
    - Residual_lag
    - Quarter_3
    - Quarter_4
    - Month_10
    - Month_3
    - Month_8
    - Trend_lag
    - Month_7
    - Month_11
    - Month_2
    - Month_9
    - Month_4
    - Month_6
    - Month_12
    - Month_5
    - Promo_Type_Cashback
    - Year
    - Promo_Type_No_Promo
    - Promo_Type_Discount
    - Quarter_2
    - New_Sales_lag_15
    params:
      lr: 0.009950363029565265
      units: 112
      batch_size: 16
      patience: 10
