results:
  linear_regression:
    features:
    - retail_sales_apparel_ewm_12_backshift_12
    - cpi_u_ewm_3_backshift_12
    - New_Sales_mean_this_year_ewm_6_backshift_12
    - New_Sales_std_this_year_ewm_12_backshift_12
    - cpi_u_backshift_12
    - Budget_USD_std_this_year_lag_3
    - New_Sales_std_this_year_ewm_6_backshift_12
    - cpi_u_lag_3_backshift_12
    - New_Sales_std_this_year_ewm_3_backshift_12
    - Budget_USD_mean_this_year_ewm_12
    - Budget_USD_std_this_year_ewm_3
    - Budget_USD_mean_this_year_ewm_6
    - Budget_USD_std_this_year_ewm_12
    - retail_sales_apparel_ewm_3_backshift_12
    - Budget_USD_std_this_year_lag_6
    - Budget_USD_std_this_year
    - Budget_USD_std_this_year_lag_12
    - cpi_u_ewm_6_backshift_12
    - gdp_ewm_3_backshift_12
    - New_Sales_std_this_year_lag_3_backshift_12
    - cpi_u_ewm_12_backshift_12
    - Budget_USD_ewm_6
    - New_Sales_ewm_6_backshift_12
    - Budget_USD_mean_this_year_ewm_3
    - New_Sales_mean_this_year_ewm_12_backshift_12
    - New_Sales_ewm_12_backshift_12
    - New_Sales_std_this_year_backshift_12
    - Budget_USD_mean_this_year
    - Budget_USD_std_this_year_ewm_6
    - New_Sales_mean_this_year_lag_3_backshift_12
    - cpi_u_lag_6_backshift_12
    - Budget_USD_mean_this_year_lag_12
    - New_Sales_std_this_year_lag_6_backshift_12
    - gdp_backshift_12
    - pce_apparel_lag_3_backshift_12
    - Quarter_2
    - retail_sales_apparel_backshift_12
    - pce_apparel_backshift_12
    - Year
    - New_Sales_mean_this_year_lag_6_backshift_12
    - pce_apparel_ewm_6_backshift_12
    - Month_4
    - Month_2
    - Quarter_3
    - quarter_cos
    - Month_7
    - Close_gold_backshift_12
    - pce_apparel_ewm_3_backshift_12
    - Month_5
    - New_Sales_lag_3_backshift_12
    - Promo_Type_Cashback
    - Promo_Type_Discount
    - Promo_Type_No_Promo
    params:
      fit_intercept: 1
      positive: 1
  lightgbm:
    features:
    - Promo_Type_No_Promo
    - quarter_cos
    - Budget_USD_ewm_3
    - month_cos
    - month_sin
    - New_Sales_lag_6_backshift_12
    - New_Sales_ewm_3_backshift_12
    - Budget_USD_std_this_year_ewm_6
    - Budget_USD_std_this_year_ewm_12
    - Budget_USD_mean_this_year_ewm_12
    - Budget_USD_mean_this_year
    - Budget_USD_ewm_6
    - New_Sales_lag_12_backshift_12
    - Budget_USD_mean_this_year_ewm_6
    - Budget_USD_ewm_12
    - New_Sales_std_this_year_ewm_12_backshift_12
    - pce_apparel_ewm_3_backshift_12
    - New_Sales_ewm_12_backshift_12
    - Budget_USD_mean_this_year_lag_12
    - Close_gold_lag_6_backshift_12
    - Month_12
    - Close_gold_backshift_12
    - Budget_USD_mean_this_year_lag_3
    - New_Sales_std_this_year_lag_3_backshift_12
    - Budget_USD_std_this_year_ewm_3
    - Month_8
    - Month_2
    - Budget_USD_std_this_year_lag_3
    - New_Sales_std_this_year_ewm_6_backshift_12
    - quarter_sin
    - New_Sales_std_this_year_backshift_12
    - Promo_Type_Discount
    - New_Sales_std_this_year_lag_6_backshift_12
    - New_Sales_ewm_6_backshift_12
    - retail_sales_apparel_ewm_12_backshift_12
    - Close_gold_ewm_6_backshift_12
    - New_Sales_mean_this_year_lag_12_backshift_12
    - New_Sales_mean_this_year_lag_6_backshift_12
    - New_Sales_mean_this_year_lag_3_backshift_12
    - Budget_USD_std_this_year
    - Year
    - Budget_USD_lag_3
    - New_Sales_mean_this_year_ewm_6_backshift_12
    - Budget_USD_lag_12
    - New_Sales_mean_this_year_ewm_3_backshift_12
    - Budget_USD_std_this_year_lag_12
    - Budget_USD_lag_6
    - Budget_USD
    - Quarter_4
    - gdp_ewm_3_backshift_12
    - cpi_u_lag_3_backshift_12
    - cpi_u_ewm_12_backshift_12
    - cpi_u_backshift_12
    - cpi_u_lag_6_backshift_12
    - gdp_backshift_12
    - Quarter_3
    - Quarter_2
    - Month_9
    - Month_7
    - Month_5
    - cpi_u_ewm_6_backshift_12
    - Month_4
    - Month_3
    - pce_apparel_backshift_12
    - Month_11
    - pce_apparel_ewm_6_backshift_12
    - pce_apparel_lag_3_backshift_12
    - Month_10
    - Promo_Type_Cashback
    - budget_to_sales_backshift_12
    - cpi_u_ewm_3_backshift_12
    - retail_sales_apparel_ewm_3_backshift_12
    - Budget_USD_std_this_year_lag_6
    - New_Sales_mean_this_year_ewm_12_backshift_12
    - Budget_USD_mean_this_year_ewm_3
    - Close_gold_ewm_12_backshift_12
    - retail_sales_apparel_backshift_12
    - Month_6
    - New_Sales_std_this_year_lag_12_backshift_12
    - New_Sales_lag_3_backshift_12
    params:
      num_leaves: 48
      max_depth: 2
      learning_rate: 0.03791577012785859
      n_estimators: 543
      subsample: 0.8137132934512264
      colsample_bytree: 0.6187656837737939
      reg_alpha: 0.00020087677526140738
      reg_lambda: 0.0004175418462172077
      min_child_samples: 11
  catboost:
    features:
    - Promo_Type_No_Promo
    - quarter_cos
    - month_sin
    - Budget_USD_ewm_3
    - month_cos
    - Budget_USD_ewm_6
    - Quarter_3
    - New_Sales_ewm_3_backshift_12
    - New_Sales_lag_6_backshift_12
    - quarter_sin
    - Budget_USD_std_this_year_ewm_6
    - New_Sales_lag_12_backshift_12
    - Budget_USD_mean_this_year_ewm_6
    - Budget_USD_std_this_year_ewm_12
    - Budget_USD_std_this_year
    - Month_8
    - Budget_USD_mean_this_year_lag_3
    - gdp_ewm_3_backshift_12
    - Budget_USD_ewm_12
    - Month_12
    - Month_9
    - Close_gold_lag_6_backshift_12
    - Budget_USD_mean_this_year_ewm_3
    - Budget_USD_std_this_year_lag_3
    - Budget_USD_mean_this_year_ewm_12
    - Budget_USD_std_this_year_ewm_3
    - pce_apparel_ewm_3_backshift_12
    - retail_sales_apparel_ewm_3_backshift_12
    - Month_11
    - New_Sales_std_this_year_ewm_3_backshift_12
    - Month_10
    - Quarter_4
    - New_Sales_std_this_year_lag_6_backshift_12
    - New_Sales_std_this_year_ewm_12_backshift_12
    - Budget_USD_mean_this_year
    - retail_sales_apparel_backshift_12
    - Quarter_2
    - Promo_Type_Discount
    - pce_apparel_lag_3_backshift_12
    - Budget_USD_mean_this_year_lag_6
    - New_Sales_std_this_year_backshift_12
    - New_Sales_std_this_year_lag_3_backshift_12
    - New_Sales_ewm_6_backshift_12
    - gdp_backshift_12
    - pce_apparel_backshift_12
    - New_Sales_lag_3_backshift_12
    - Month_4
    - Close_gold_ewm_12_backshift_12
    - Month_7
    - New_Sales_mean_this_year_lag_3_backshift_12
    - Close_gold_ewm_6_backshift_12
    - cpi_u_ewm_3_backshift_12
    - New_Sales_mean_this_year_lag_12_backshift_12
    - cpi_u_ewm_6_backshift_12
    - pce_apparel_ewm_6_backshift_12
    - New_Sales_mean_this_year_lag_6_backshift_12
    - Budget_USD_lag_12
    - Budget_USD_lag_3
    - Year
    - Budget_USD_lag_6
    - Budget_USD
    - budget_to_sales_backshift_12
    - cpi_u_ewm_12_backshift_12
    - cpi_u_lag_6_backshift_12
    - cpi_u_backshift_12
    - Month_2
    - cpi_u_lag_3_backshift_12
    - Month_3
    - Promo_Type_Cashback
    - Month_5
    - New_Sales_std_this_year_ewm_6_backshift_12
    - New_Sales_mean_this_year_backshift_12
    - New_Sales_ewm_12_backshift_12
    - Close_gold_backshift_12
    - Budget_USD_std_this_year_lag_6
    - Budget_USD_mean_this_year_lag_12
    - New_Sales_mean_this_year_ewm_12_backshift_12
    - Budget_USD_std_this_year_lag_12
    - New_Sales_mean_this_year_ewm_6_backshift_12
    - New_Sales_mean_this_year_ewm_3_backshift_12
    params:
      depth: 4
      learning_rate: 0.04109165773520847
      iterations: 682
      l2_leaf_reg: 1.044668627867743
      random_strength: 4.3668247423947735
      bagging_temperature: 0.5545358176701942
      border_count: 252
      rsm: 0.9877731843740087
  lstm:
    features:
    - Quarter_3
    - New_Sales_lag_12
    - Quarter_4
    - New_Sales_lag_15
    - Promo_Type_Discount
    - Month_8
    - Month_3
    - Month_6
    - Month_9
    - Month_10
    - Month_11
    - Month_12
    - Month_4
    - Month_2
    - Month_7
    - Promo_Type_Cashback
    - Year
    - Budget_USD
    - Month_5
    - Quarter_2
    params:
      lr: 0.008998651044480825
      units: 64
      batch_size: 16
      patience: 8
  rnn:
    params:
      lr: 0.009347386270384209
      units: 112
      batch_size: 16
      patience: 10
